# skills
# See:
#  - https://skills.sh/
#  - https://github.com/vercel-labs/skills
sourcePath: ~/.agents/skills/**/*/SKILL.md
name: "{frontmatter@name}"
label: "skills / {pathdir:1}"
description: "{frontmatter@description}"
color: blue
triggers: ["/","$"]