name: "{frontmatter@name}"
pluginDescription: ~/.agents/skills/
description: "{frontmatter@description}"
path: ~/.agents/skills/
label: "agents-skills"
color: blue
pattern: "**/*/SKILL.md"
triggers: ["/","$"]